//! The player table: which media players Ryuuji recognises and how each
//! strategy identifies them. The table ships embedded in the binary.

use serde::Deserialize;

#[derive(Clone, Debug, PartialEq, Eq, Deserialize)]
pub(crate) struct Player {
    pub name: String,
    /// Substrings of the SMTC source app user model id, lowercased by
    /// [`PlayerTable::parse`] so a match only has to lowercase the app id.
    #[serde(default)]
    pub smtc_app_ids: Vec<String>,
    /// File names of the player's executables, lowercased by
    /// [`PlayerTable::parse`]. The foreground window is tied to a player by
    /// this name alone, so two instances of one player read the same.
    #[serde(default)]
    pub executables: Vec<String>,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub(crate) struct PlayerTable {
    players: Vec<Player>,
}

#[derive(Debug, thiserror::Error)]
pub(crate) enum TableError {
    #[error("players.toml does not parse")]
    Parse(#[source] toml::de::Error),
    #[error("player {name:?} has a {field} entry shorter than 3 characters: {pattern:?}")]
    ShortPattern {
        name: String,
        field: &'static str,
        pattern: String,
    },
    #[error("player name {name:?} appears twice")]
    DuplicateName { name: String },
}

const MIN_PATTERN_LEN: usize = 3;

#[derive(Deserialize)]
struct Document {
    #[serde(default)]
    player: Vec<Player>,
}

impl PlayerTable {
    /// The embedded table; a parse failure is a build defect covered by a test.
    pub(crate) fn builtin() -> PlayerTable {
        PlayerTable::parse(include_str!("players.toml")).expect("embedded players.toml is valid")
    }

    pub(crate) fn parse(text: &str) -> Result<PlayerTable, TableError> {
        let document: Document = toml::from_str(text).map_err(TableError::Parse)?;
        let mut players = document.player;
        for (index, player) in players.iter().enumerate() {
            for (field, patterns) in [
                ("smtc_app_ids", &player.smtc_app_ids),
                ("executables", &player.executables),
            ] {
                if let Some(pattern) = patterns
                    .iter()
                    .find(|pattern| pattern.chars().count() < MIN_PATTERN_LEN)
                {
                    return Err(TableError::ShortPattern {
                        name: player.name.clone(),
                        field,
                        pattern: pattern.clone(),
                    });
                }
            }
            if players[..index]
                .iter()
                .any(|earlier| earlier.name == player.name)
            {
                return Err(TableError::DuplicateName {
                    name: player.name.clone(),
                });
            }
        }
        for pattern in players
            .iter_mut()
            .flat_map(|p| p.smtc_app_ids.iter_mut().chain(&mut p.executables))
        {
            *pattern = pattern.to_lowercase();
        }
        Ok(PlayerTable { players })
    }

    #[cfg(test)]
    pub(crate) fn players(&self) -> &[Player] {
        &self.players
    }

    /// Case-insensitive substring match of any pattern against the app id;
    /// first table entry wins.
    pub(crate) fn match_smtc(&self, app_id: &str) -> Option<&Player> {
        let app_id = app_id.to_lowercase();
        self.players.iter().find(|player| {
            player
                .smtc_app_ids
                .iter()
                .any(|pattern| app_id.contains(pattern))
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn names(table: &PlayerTable) -> Vec<&str> {
        table.players().iter().map(|p| p.name.as_str()).collect()
    }

    #[test]
    fn builtin_table_parses_with_mpv_vlc_and_mpc_hc_in_order() {
        assert_eq!(names(&PlayerTable::builtin()), ["mpv", "VLC", "MPC-HC"]);
    }

    #[test]
    fn match_is_case_insensitive_and_substring() {
        let table = PlayerTable::builtin();
        for app_id in [
            "MPV.EXE",
            "C:\\tools\\mpv.exe",
            "Microsoft.AutoGenerated.{8B7C2A1E-0000-4000-8000-000000000000}\\mpv.exe",
        ] {
            assert_eq!(
                table.match_smtc(app_id).map(|p| p.name.as_str()),
                Some("mpv")
            );
        }
    }

    #[test]
    fn parse_lowercases_patterns_so_an_uppercase_entry_still_matches() {
        let table = PlayerTable::parse(
            "[[player]]\nname = \"MPV\"\nsmtc_app_ids = [\"MPV.EXE\"]\nexecutables = [\"MPV.EXE\"]\n",
        )
        .unwrap();
        assert_eq!(table.players()[0].smtc_app_ids, ["mpv.exe"]);
        assert_eq!(table.players()[0].executables, ["mpv.exe"]);
        assert_eq!(
            table
                .match_smtc("C:\\tools\\mpv.exe")
                .map(|p| p.name.as_str()),
            Some("MPV")
        );
    }

    #[test]
    fn every_builtin_player_names_an_executable() {
        for player in PlayerTable::builtin().players() {
            assert!(!player.executables.is_empty(), "{}", player.name);
        }
    }

    #[test]
    fn unknown_app_id_matches_nothing() {
        assert_eq!(PlayerTable::builtin().match_smtc("Spotify.exe"), None);
    }

    #[test]
    fn pattern_shorter_than_three_chars_is_rejected_and_names_the_field() {
        for field in ["smtc_app_ids", "executables"] {
            let result =
                PlayerTable::parse(&format!("[[player]]\nname = \"x\"\n{field} = [\"ab\"]\n"));
            assert!(
                matches!(
                    result,
                    Err(TableError::ShortPattern { ref name, field: got, ref pattern })
                        if name == "x" && got == field && pattern == "ab"
                ),
                "{field}: {result:?}"
            );
        }
    }

    #[test]
    fn duplicate_player_name_is_rejected() {
        let text = "[[player]]\nname = \"mpv\"\nsmtc_app_ids = [\"mpv.exe\"]\n\
                    [[player]]\nname = \"mpv\"\nsmtc_app_ids = [\"mpv2.exe\"]\n";
        assert!(matches!(
            PlayerTable::parse(text),
            Err(TableError::DuplicateName { ref name }) if name == "mpv"
        ));
    }

    #[test]
    fn missing_id_lists_are_empty() {
        let table = PlayerTable::parse("[[player]]\nname = \"bare\"\n").unwrap();
        assert_eq!(
            table.players(),
            [Player {
                name: "bare".to_owned(),
                smtc_app_ids: Vec::new(),
                executables: Vec::new(),
            }]
        );
        assert_eq!(table.match_smtc("bare"), None);
    }
}
