[package]
name = "ryuuji-core"
description = "Platform-independent application state for Ryuuji"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
rusqlite.workspace = true
rusqlite_migration.workspace = true
directories.workspace = true
tracing.workspace = true
thiserror.workspace = true

[dev-dependencies]
tempfile.workspace = true
